name = "AutoViz"
uuid = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
repo = "https://github.com/sisl/AutoViz.jl.git"
version = "0.7.10"

[deps]
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rsvg = "c4c386cf-5103-5370-be45-f3a111cca3b8"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Interact", "NBInclude", "Random", "Reactive", "Test"]
